pipeline {
    agent any

    environment {
        DOCKER = 'C:\\Users\\aavan\\AppData\\Local\\Programs\\DockerDesktop\\resources\\bin\\docker.exe'
    }

    stages {
        stage('Build') {
            steps {
                bat '"%DOCKER%" build -t task2-node-app .'
            }
        }

        stage('Test') {
            steps {
                bat 'npm install'
                bat 'npm test'
            }
        }

        stage('Deploy') {
            steps {
                bat '"%DOCKER%" rm -f task2-node-app || exit /b 0'
                bat '"%DOCKER%" run -d --name task2-node-app -p 3000:3000 task2-node-app'
            }
        }
    }
}
