pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bat 'docker build -t task2-node-app .'
            }
        }

        stage('Test') {
            steps {
                bat 'npm install'
                bat 'npm test'
            }
        }

        stage('Deploy') {
            steps {
                bat 'docker rm -f task2-node-app || exit /b 0'
                bat 'docker run -d --name task2-node-app -p 3000:3000 task2-node-app'
            }
        }
    }
}
